<?php

/**
 * @file
 * Define install and uninstall hooks
 */


/**
 * Create the 'Parsedown' format on install.
 */
function parsedown_install() {
    $t = get_t();

    $format = (object) array();

    $format->name = $t('Parsedown');
    $format->format = 'parsedown';

    $format->status = 1;

    $format->filters = array(
        'parsedown' => array(
            'status' => 1,
        ),
    );

    filter_format_save($format);
}
